- source/receiving-updates.md
> Adding documentation for receiving updates

- source/index.md
Sashko I kind of wimped out on the comparison section, partly because I think you've thought about this a lot and should probably just write this.
Also:
1. Should I expand the "goals" section? I think it mirrors what you've written before but with less detail
2. I removed the "Apollo is currently in the technical preview" paragraph. I think this fair?
3. The last index had a big list of examples. We will go into a lot of details about the GitHunt example in a section to come, I don't know if we want to mention the others still (or at least the React ones?)
> Introduction

- source/cache-updates.md
Documentation for `fetchMore`. Fixes #14.
> Fetch more docs

- source/queries.md
The content came in a few commits, but this gives us one branch to comment on.
This reverts commit 73f18f64ffc5474d6ab7a3c122f86a5c829870e1.
> Queries section

- source/initialization.md
Mostly just other content pulled together. Not sure about the final sections.
> Initialization

- source/prefetching.md
> Prefetching

- source/example-schema.md
> Added latest githunt schema

- source/cache-updates.md
> Added a section about dataIdFromObject

- source/redux.md
If I'm following the code properly, it needs to call `ownProps.onSelectList` instead of `ownProps.viewList`.
Thanks!
> Redux connect mutation example update

- source/queries.md
Depends on https://github.com/apollostack/react-apollo/pull/253 being live!
> Add new skip api

- source/mutations.md
As requested (note: code fragment not tested, yet)
> Added a note about how to do multiple mutations on a component.

- source/cache-updates.md
- source/index.md
(courtesy of Tom@slack for how to)
Note: I would have liked to update the core-docs as well to fix up the apparent typo around addTypeName, and add more information about it there, then link to here.
But I couldn't quickly work out how to edit core-docs (%tsapibox%)
> Clarifications and more examples for "Controlling The Store" (dataIdFromObject and updateQueries)

- _config.yml
- source/webpack.md
- webpack.md
As per https://github.com/apollostack/graphql-tag/pull/13
> add webpack loader recipe

- source/webpack.md
Sorry! I didn't realize it over the past PR #84
> remove unnecessary doc section

- source/pagination.md
#52 
This PR adds an example of pagination using relay-style cursors and is based heavily on the example already provided for 'basic' cursor pagination.
> Add Relay-style cursor example to pagination

- source/higher-order-components.md
Documented existence of compose function and provided usage example.
> Document usage of compose

- source/mutations.md
`submit` method should return function to invoke by onClick event
> submit method return function

- source/fragments.md
@stubailo here are the text changes to the docs
> Update fragments text to no longer use `grapghql-fragments`

- source/receiving-updates.md
Both mutation options are related to the subject of getting updates from the server.
> Added mention to mutation triggered query refetch/update.

- source/queries.md
> Updated queries.md

- source/server-side-rendering.md
@helfer suggested adding a section to the docs in [this issue](https://github.com/apollostack/apollo-client/issues/962#issuecomment-266645184)
> Add note about `apollo-local-query` in SSR docs

- source/cache-updates.md
- source/optimistic-ui.md
changed to `immutability-helper` as per https://facebook.github.io/react/docs/update.html
> removed deprecated react-addons-update

- source/server-side-rendering.md
I had to modify the code snippet from the docs a bit to get rehydration working. I've updated the respective sections with the code that worked for me.
Did the API change at some point?
> Updated rehydration code snippets.

- source/higher-order-components.md
> should resubscribe props change

- source/webpack.md
see discussion in https://github.com/apollographql/graphql-tag/pull/33
> updated webpack.md with info on #import syntax for fragments

- source/fragments.md
See https://github.com/apollographql/apollo-client/issues/940
> Remove outdated note about warning

- source/cache-updates.md
Based on https://github.com/apollographql/apollo-client/issues/1013
> Correct reducer documentation

- source/api.md
- source/cache-updates.md
- source/pagination.md
apollographql/apollo-client#1416
> Remove data property from fetchMore result

- source/api.md
Includes arguments and an example code snippet.
> Added `subscribeToMore` docs to `api.md`

- source/cache-updates.md
Currently it is not clear what is it. Is it a special keyword or some magic or something else.
In my case it was "Root" and I spent pretty much time trying to understand why `customResolvers` are not working for me.
> Clarify what is "Query" key in `customResolvers` example

- source/api.md
- source/cache-updates.md
apollographql/apollo-client#1455
> Update subscribeToMore specifying the updateQuery option as optional

- source/api-mutations.md
fairly sure it should be mutation.
> FIX: said query went meant mutation

- source/simple-example.md
> Fixed spelling typo

- source/server-side-rendering.md
See these docs for rationale:
http://redux.js.org/docs/recipes/ServerRendering.html#security-considerations|
> Sanitize JSON.stringify output to prevent XSS

- source/cache-updates.md
And links to the relevant bit in the Vanilla JS section.
> Adds a minimal mention of Direct Cache Access

- source/api-queries.md
Just a tiny typo I spotted while reading the docs.
Thank you for the great project and docs!
> Fix a typo

- source/api-queries.md
Not sure should update the example though.
> docs(api): Add docs for variables argument in docs of data.refetch

- package.json
Reverts apollographql/react-docs#213
> Revert "Update hexo to the latest version 🚀"

- source/cache-updates.md
Check for `fetchMoreResult`, not `fetchMoreResult.data`.
> Update fetchMore docs

- source/mutations.md
Just a quick change to the "multiple mutations" code snippet, to match the formatting style of other code snippets.
> update mutations.md formatting

- source/cache-updates.md
availble -> available
respositories -> repositories
> Fix typos in cache-updates.md

- source/subscriptions.md
By specifying that it should have the same shape as the original query data.
> Document the expected updateQuery return value

- source/server-side-rendering.md
> Only send request cookie rather than full headers

- source/simple-example.md
Fixes [this page](http://dev.apollodata.com/react/simple-example.html)'s broken link.
> Fix broken link in simple-example

- source/api-mutations.md
Changed "excepted" to "accepted".
> Fixed typo in api-mutations.md

- source/subscriptions.md
> Minor typo fix

- source/cache-updates.md
Add note about having to be the same data, add note about where to get `__typename`, improve overall documentation.
> Sidenote: I feel like `customResolvers` isn't a super great name since it's not like it replaces a resolver on the backend, it helps apollo resolve something from the client cache. What about renaming it to `cacheResolvers` instead?
> Improve customResolvers documentation

- source/using-with-types.md
Adjusted flow docs around classes to be more accurate
> update class for flow since it can infer

- source/simple-example.md
Move to the updated link on howtographql.com as learnapollo.com is deprecated. Please let me know if I need to change the label as well or if this is not relevant.
> Updated simple-example.md

- source/auth.md
change `forceFetch: true` to `fetchPolicy: 'network-only'`
> forceFetch -> fetchPolicy

- source/server-side-rendering.md
Removes note which referenced previous version of GitHunt-React app.
> [RFR] Update SSR section again

- source/webpack.md
Hello,
I wanted to separate my graphql queries into proper files on my react-native project, but no webpack available…
So after some research, I would like to add the solution for the next one 😉
> Add React native case
