source/cache-updates.md

Documentation for `updateQueries` (i.e. updating query results with the result of a mutation). Should eventually fix #15.

`updateQueries` documentation

---

source/redux.md

I didn't include a lot of the thunk content from http://docs.apollostack.com/apollo-client/redux.html because it doesn't seem like you'd use it w/ `react-apollo`. Perhaps we want to keep it for the "raw" Client docs? I'm not sure.

Basic redux docs

---

source/mutations.md

I'm pretty sure that `gql` needs to be imported as the default from graphql-tag instead of as a named import.

gql import fix for mutations

---

source/queries.md

Update the code example syntax for using `props` in `graphql` to map props. The example as given errors.

Update `props` example in queries.md

---

source/receiving-updates.md

Note: the example here was misleading:
```javascript
const FeedWithData = graphql(FeedEntries, {
options: {
return { pollInterval: 20000 };
},
})(Feed);
```
I believe that it was supposed to be either a lambda that returns an object, or just a plain object without the `return` so I updated it to
```javascript
const FeedWithData = graphql(FeedEntries, {
options: { pollInterval: 20000 },
})(Feed);
```

Fix: the query options example is misleading

---

source/react-native.md

With the idea that a common way people get to this page is clicking "React Native":
And they don't know they're already technically inside the React guide

react-native.md: link to the "React guide"

---

source/receiving-updates.md

Figured out looking at the [test](https://github.com/apollostack/apollo-client/blob/master/test/subscribeToMore.ts#L69) that subscribeToMore accepts the subscription query via the `document` key.

subscribeToMore accepts document key for the query

---

source/server-side-rendering.md

Got this notification following the docs:
Passing the URI as the first argument to createNetworkInterface is deprecated as of Apollo Client 0.5. Please pass it as the "uri" property of the network interface options.
Docs updated with new uri added and first argument removed.
ps: great work on Apollo!

Update SSR doc to reflect change in createNetworkInterface

---

source/pagination.md

Functional components don't have `this.props`.

Fix a typo in pagination examples

---

source/cache-updates.md

Probably just a typo. 
Also, I'm not sure where the ```dataIdFromObject``` should be imported from.

Remove unneeded backtick in cache-updates.md

---

source/higher-order-components.md
source/redux.md

* Mutations require a selection set.
* Change `’true’` string to `true` boolean.
* Fix the props of `List` in the Redux example.

Fix a few code examples

---

source/auth.md

Passing a string results in the warning:
"Passing the URI as the first argument to createNetworkInterface is deprecated as of Apollo Client 0.5. Please pass it as the "uri" property of the network interface options."

Pass an object rather than a string to prevent warning

---

source/optimistic-ui.md

I think it would be helpful to make it clear that params of `updateQueries` first arg are the names of queries. 
In the example in the docs, there is an implied query named Comment, but the type Comment is also returned by the `submitComment` mutation. It wasn't clear to me that the param refers to queries and not the return type of the mutation, especially since the `optimisticResponse` params are all about type. Took investigating the docs to realize why updateQueries wasn't executing.
The easiest way I can think of showing this without making the example more complex is just renaming the query :)

change implied query name to reduce confusion

---

source/redux.md

As https://github.com/zalmoxisus/redux-devtools-extension#usage docs states, `window.devToolsExtension` has been renamed and will be deprecated in the future. I just stumbled upon this, while setting up my latest project, so I'm not sure if I can just propose a change like this here.. Let me know in case I'm trying to contribute in a wrong way.
And keep up the great work, Apollo Client is awesome!

Update Redux devtools setup syntax

---

source/redux.md

The original `window.__REDUX_DEVTOOLS_EXTENSION__ && ...` was breaking my app in browsers without this extension.
I'm not sure how other parts of my app are influencing the problem that is caused by this but I can't be alone. I'm using create-react-app not ejected.

use typeof to check for redux devtools

---

source/receiving-updates.md

Remove reference to future subscriptions feature which is already available in the Apollo client.

Remove reference to future subscriptions feature

---

source/cache-updates.md

Added that
1. it is possible to return list of ids #508 https://github.com/apollographql/react-apollo/issues/508
2. it is possible to dynamically skip cache by returning `toIdValue(null)` or `[toIdValue(null)]`. Actually I'm not sure that it is legal way to do it, but it works :)

Update `customResolvers` docs

---

source/initialization.md

Replaces a bogus `,` for an end-of-line `;` in client instantiation example

Fixes code example

---

source/api-queries.md

Add a small note about using `option.notifyOnNetworkStatusChange` in the `query` function.

Add note for options.notifyOnNetworkStatusChange

---

source/api-mutations.md

`source/api-mutations.md` has a typo for the word `response` (typed as `respone`).
This PR fixes the typo and adds a hyphen to refer to the possible response types it refers to afterward.

Fix 'response' typo & add hyphen to refer to possible response types

---

source/fragments.md

Add `import` syntax mention in the `fragments` section
Link to `webpack` page where further usage / details are provided
Closes #185

docs(fragments): Document import syntax

---

source/api-server.md

Links to `server-side-rendering.html` had an extra `#` in front.

Fix links to server side rendering recipe

---

source/cache-updates.md

As discussed in [apollographql/apollo-client#1657 (comment)](https://github.com/apollographql/apollo-client/issues/1657#issuecomment-299536799)
Merge after apollographql/apollo-client#1663
CC: @helfer

Add docs for the exposure of 'dataIdFromObject' and 'dataId'

---

source/auth.md

I think it will be really helpful to mention that `withApollo` HOC is needed to access `client`.

Update auth.md - add info about "withApollo"

---

source/api-mutations.md

The current link goes to http://dev.apollodata.com/react/#graphql-mutation-options-update whereas it should go to http://dev.apollodata.com/react/api-mutations.html#graphql-mutation-options-update.

Updated incorrect link to Mutations: Update

---

source/receiving-updates.md

>@deep-c It's not defined because you're not actually getting an observable back. Apollo Client subscribes to it for you, so all you get back is actually the unsubscribe handle. So if you call this.subscription() it will unsubscribe. Maybe the variable name I chose in GitHunt-React isn't great 😄 . Would be better to call it unsubscribeHandle or something.
https://github.com/apollographql/apollo-client/issues/1145#issuecomment-271566605

subscribeToMore returns unsubscribe handler

---

source/subscriptions.md

People don't usually use `http://localhost:3000/` as their endpoint for graphql,
I think it might be more understandable what it is if we use `http://localhost:3000/graphql` as example.

Change the endpoint URI example to the less misleading one

---

source/api-graphql.md
source/api-queries.md

I noticed a couple of the anchor links were not pointing to their correct URLs, this should fix the problem! I _believe_ the second commit also fixes the broken generic `config.options` link, but I wasn't 100% sure if it was pointing to the correct reference.

Fix broken `config.option` links

---

source/auth.md

gql is used to create the graphql query for the Profile component so it has to be imported to work.

Add gql to the list of imports

---

source/webpack.md

I have been using apollo-client and webpack on a project, but we are switching to use the FuseBox bundler and had to create a plugin to work with your webpack loader. I saw the link for the Jest loader and thought I might share the FuseBox loader here as well.

Add link to FuseBox plugin

---

source/pagination.md

The example suggested that `cursor` would be returned alongside `moreComments`, but in reality the cursor is returned as a field of `moreComments`.
I also updated some ambiguous naming

fix example; cursor is not available on root

---

source/optimistic-ui.md

The previous example is actually only implementing `optimisticResponse` but then the next example implements `update` as well as `optimisticResponse`, and I found the wording to be a bit confusing around this. Do we need to implement `update` as well as `optimisticResponse` as the example shows for adding to a list? If so, the wording was incorrect. If not, then it'd be ideal to give an example where only `optimisticResponse` is required for adding to a list.
I'm currently assuming that the wording was actually slightly off, and that `update` was in fact necessary, in which case we can just remove the bit about `update` not being required.

Remove wording about "just like above"

---

source/server-side-rendering.md

The existing docs show an example using React Router v3, which has a pretty different API than v4. I just got this working for v4, so let me know if anything seems unclear.

Update SSR for React docs to reflect newest version of React Router

---

source/cache-updates.md

In found a small typo in the example while reading the docs.

Fixed small typo in example

---

source/cache-updates.md

Small typo in refetchQueries example. The variable name is incorrect in the mutation of refetchQueries example.

Small typo in refetchQueries example

---

source/cache-updates.md

There was unnecessary escaping, breaking the link.
🎉

Fix internal link

---

source/auth.md

This PR fixes couple of minor issues in `auth.md`.
1. Remove unexpected `;` from an example
2. Use the `ApolloClient` in `react-apollo` instead of `apollo-client`. If one is using `react-apollo`, chances are that they are also using the `ApolloClient` in the same package instead of the standalone one. The current example fails the proptype check in this case, as `client` is an instance of the `ApolloClient` in `react-apollo`, which raises quite 🤔 error message too (`Warning: Invalid prop `client` of type `ApolloClient` supplied to `Foo`, expected instance of `ApolloClient`).

Update auth.md with minor fixes

---

source/fragments.md

The component field is named `fragments`, not `fragment`.

fragment -> fragments

---

source/api-queries.md

add brief note to clear any variables that were set before for any query. This is helpful when you want to omit a variable from the query that was set before. e.g in case of filters you might want to clear previous filter variable but by not passing that variable will result in picking the old value.

add note about refetch variables
